# Generated by Django 6.0.3 on 2026-04-06 16:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('student', 'Студент'), ('company', 'Компания')], default='student', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пайдаланушы',
                'verbose_name_plural': 'Пайдаланушылар',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Толық аты')),
                ('expected_salary', models.IntegerField(verbose_name='Күтілетін жалақы')),
                ('about_me', models.TextField(verbose_name='Мен туралы')),
                ('university_name', models.CharField(max_length=255, verbose_name='Университет')),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='GPA')),
                ('skills', models.TextField(verbose_name='Дағдылар')),
                ('experience', models.TextField(blank=True, null=True, verbose_name='Тәжірибе')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Электрондық пошта')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CV-лер',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Жұмыс атауы')),
                ('salary', models.IntegerField(verbose_name='Жалақы')),
                ('city', models.CharField(max_length=100, verbose_name='Қала')),
                ('employment_type', models.CharField(choices=[('full_time', 'Толық уақыт'), ('part_time', 'Жартылай уақыт')], max_length=20, verbose_name='Жұмыс түрі')),
                ('work_format', models.CharField(choices=[('remote', 'Қашықтан'), ('onsite', 'Офисте')], max_length=20, verbose_name='Жұмыс форматы')),
                ('description', models.TextField(verbose_name='Сипаттама')),
                ('requirements', models.TextField(verbose_name='Талаптар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыты')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бос орын',
                'verbose_name_plural': 'Бос орындар',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Күтуде'), ('accepted', 'Қабылданды'), ('rejected', 'Бас тартылды')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.vacancy')),
            ],
            options={
                'verbose_name': 'Өтініш',
                'verbose_name_plural': 'Өтініштер',
            },
        ),
    ]
